//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLt.Net.Legacy.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeLt.Net.Legacy.UI.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutMe.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Real Villa.
        /// </summary>
        public static string AboutRealVilla {
            get {
                return ResourceManager.GetString("AboutRealVilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Villa helped thousands of clients to find the right property for their needs..
        /// </summary>
        public static string AboutRealVillaSubText {
            get {
                return ResourceManager.GetString("AboutRealVillaSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Listing.
        /// </summary>
        public static string AddListing {
            get {
                return ResourceManager.GetString("AddListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filter.
        /// </summary>
        public static string AdvancedFilter {
            get {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Properties.
        /// </summary>
        public static string ApprovedProperties {
            get {
                return ResourceManager.GetString("ApprovedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        public static string Bedrooms {
            get {
                return ResourceManager.GetString("Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse By Category.
        /// </summary>
        public static string BrowseByCategory {
            get {
                return ResourceManager.GetString("BrowseByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Sale.
        /// </summary>
        public static string DirectSale {
            get {
                return ResourceManager.GetString("DirectSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Our Best Deals.
        /// </summary>
        public static string DiscoverOurBestDeals {
            get {
                return ResourceManager.GetString("DiscoverOurBestDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the listings of the best dealer on Real Villa and contact the agency or its agent by phone or contact form..
        /// </summary>
        public static string DiscoverOurBestDealsSubText {
            get {
                return ResourceManager.GetString("DiscoverOurBestDealsSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t have an account? Register Now!.
        /// </summary>
        public static string DoesntHaveAnAccount {
            get {
                return ResourceManager.GetString("DoesntHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent Reputation.
        /// </summary>
        public static string ExcellentReputation {
            get {
                return ResourceManager.GetString("ExcellentReputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our comprehensive database of listings and market info give the most accurate view of the market and your home value..
        /// </summary>
        public static string ExcellentReputationSubText {
            get {
                return ResourceManager.GetString("ExcellentReputationSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get notified.
        /// </summary>
        public static string GetNotified {
            get {
                return ResourceManager.GetString("GetNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Sign in with.
        /// </summary>
        public static string LoginOrSignInWith {
            get {
                return ResourceManager.GetString("LoginOrSignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery Results.
        /// </summary>
        public static string LotteryResult {
            get {
                return ResourceManager.GetString("LotteryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery Sale.
        /// </summary>
        public static string LotterySale {
            get {
                return ResourceManager.GetString("LotterySale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.Price.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.Price.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about us.
        /// </summary>
        public static string MoreAboutUs {
            get {
                return ResourceManager.GetString("MoreAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular Places.
        /// </summary>
        public static string MostPopularPlaces {
            get {
                return ResourceManager.GetString("MostPopularPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Properties.
        /// </summary>
        public static string MyProperties {
            get {
                return ResourceManager.GetString("MyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tickets.
        /// </summary>
        public static string MyTickets {
            get {
                return ResourceManager.GetString("MyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly Listed Properties.
        /// </summary>
        public static string NewlyListedProperties {
            get {
                return ResourceManager.GetString("NewlyListedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News, Tips &amp; Articles.
        /// </summary>
        public static string NewsTips_Articles {
            get {
                return ResourceManager.GetString("NewsTips&Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Approved Properties.
        /// </summary>
        public static string NonApprovedProperties {
            get {
                return ResourceManager.GetString("NonApprovedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Again.
        /// </summary>
        public static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency.
        /// </summary>
        public static string Residency {
            get {
                return ResourceManager.GetString("Residency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Properties.
        /// </summary>
        public static string SavedProperties {
            get {
                return ResourceManager.GetString("SavedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Details.
        /// </summary>
        public static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Us.
        /// </summary>
        public static string SubscribeUs {
            get {
                return ResourceManager.GetString("SubscribeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to our newsletter to get the latest news and offers..
        /// </summary>
        public static string SubscribeUsSubText {
            get {
                return ResourceManager.GetString("SubscribeUsSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Listings.
        /// </summary>
        public static string ViewAllListings {
            get {
                return ResourceManager.GetString("ViewAllListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plenty Of Reasons To Choose Us.
        /// </summary>
        public static string WhyChooseUs {
            get {
                return ResourceManager.GetString("WhyChooseUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our agency has many specialized areas, but our CUSTOMERS are our real specialty..
        /// </summary>
        public static string WhyChooseUsSubText {
            get {
                return ResourceManager.GetString("WhyChooseUsSubText", resourceCulture);
            }
        }
    }
}
