// <auto-generated />
namespace HomeLt.Net.Legacy.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010081344391_v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
